## DataFrame 인덱싱 1

- 데이터 여러줄 받아오기

In [2]:
import pandas as pd
iphone_df = pd.read_csv('C:/Users/jaewoo/Desktop/data science/data/iphone.csv', index_col = 0)
iphone_df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [3]:
iphone_df.loc[['iPhone X', 'iPhone 8']]

                 출시일  디스플레이  메모리     출시 버전 Face ID
iPhone X  2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone 8  2017-09-22    4.7  2GB  iOS 11.0      No

In [4]:
type(iphone_df.loc[['iPhone X', 'iPhone 8']])

pandas.core.frame.DataFrame

In [5]:
iphone_df[['Face ID', '출시일', '메모리']]

              Face ID         출시일  메모리
iPhone 7           No  2016-09-16  2GB
iPhone 7 Plus      No  2016-09-16  3GB
iPhone 8           No  2017-09-22  2GB
iPhone 8 Plus      No  2017-09-22  3GB
iPhone X          Yes  2017-11-03  3GB
iPhone XS         Yes  2018-09-21  4GB
iPhone XS Max     Yes  2018-09-21  4GB

In [7]:
iphone_df.loc['iPhone 8':'iPhone XS']

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes

In [8]:
iphone_df.loc[:'iPhone XS']

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes

In [10]:
iphone_df.loc[:, '메모리' : 'Face ID']

               메모리     출시 버전 Face ID
iPhone 7       2GB  iOS 10.0      No
iPhone 7 Plus  3GB  iOS 10.0      No
iPhone 8       2GB  iOS 11.0      No
iPhone 8 Plus  3GB  iOS 11.0      No
iPhone X       3GB  iOS 11.1     Yes
iPhone XS      4GB  iOS 12.0     Yes
iPhone XS Max  4GB  iOS 12.0     Yes

In [11]:
iphone_df.loc['iPhone 7':'iPhone X', '메모리' : 'Face ID']

               메모리     출시 버전 Face ID
iPhone 7       2GB  iOS 10.0      No
iPhone 7 Plus  3GB  iOS 10.0      No
iPhone 8       2GB  iOS 11.0      No
iPhone 8 Plus  3GB  iOS 11.0      No
iPhone X       3GB  iOS 11.1     Yes

## 실습과제 _ 방송사 시청률 받아오기4

이번에는 DataFrame에서 연속된 여러 줄을 찾는 연습을 해보겠습니다.

방송사는 'KBS'에서 'SBS'까지, 연도는 2012년부터 2017년까지의 시청률만 확인하려면 어떻게 하면 될까요?

In [12]:
import pandas as pd

df = pd.read_csv('C:/Users/jaewoo/Desktop/data science/data/broadcast.csv', index_col = 0)

# 코드를 작성하세요.
df.loc[2012 : 2017, 'KBS' : 'SBS']

         KBS     MBC     SBS
2012  36.163  16.022  11.408
2013  31.989  16.778   9.673
2014  31.210  15.663   9.108
2015  27.777  16.573   9.099
2016  27.583  14.982   8.669
2017  26.890  12.465   8.661